name: Update GitHub Actions versions

on:
  schedule:
    - cron: "51 4 * * *"
  workflow_dispatch:

concurrency:
  group: update
  cancel-in-progress: true

permissions:
  contents: write # needed to commit

jobs:
  update-versions:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Set up Python
        uses: actions/setup-python@83679a892e2d95755f2dac6acb0bfd1e9ac5d548 # v6.1.0
        with:
          python-version: "3.12"

      - name: Run tests
        run: python -m unittest test_fetch_versions -v

      - name: Run fetch_versions.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: python fetch_versions.py

      - name: Commit changes
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git add versions.txt versions-sha.txt unversioned.txt
          git diff --staged --quiet || git commit -m 'chore: update versions'
          git push
